attribute(faixa, [i16_30, i31_50, i51_mais]).
attribute(dieta, [geral, ligeira, ovo_lacteo_vegetariana, vegana, fast_food]).
attribute(zona, [norte_centro, lisboa_vale_tejo, alentejo_algarve]).
attribute(proteina, [carne, peixe, ovo]).

:- dynamic example/2.

example(1, [faixa=i16_30, dieta=geral, zona=norte_centro, proteina=carne]).
example(2, [faixa=i16_30, dieta=ligeira, zona=norte_centro, proteina=carne]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=carne]).
example(4, [faixa=i16_30, dieta=vegana, zona=norte_centro, proteina=carne]).
example(5, [faixa=i16_30, dieta=fast_food, zona=norte_centro, proteina=carne]).
example(1, [faixa=i16_30, dieta=geral, zona=lisboa_vale_tejo, proteina=carne]).
example(6, [faixa=i16_30, dieta=ligeira, zona=lisboa_vale_tejo, proteina=carne]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=carne]).
example(4, [faixa=i16_30, dieta=vegana, zona=lisboa_vale_tejo, proteina=carne]).
example(5, [faixa=i16_30, dieta=fast_food, zona=lisboa_vale_tejo, proteina=carne]).
example(7, [faixa=i16_30, dieta=geral, zona=alentejo_algarve, proteina=carne]).
example(8, [faixa=i16_30, dieta=ligeira, zona=alentejo_algarve, proteina=carne]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=carne]).
example(4, [faixa=i16_30, dieta=vegana, zona=alentejo_algarve, proteina=carne]).
example(5, [faixa=i16_30, dieta=fast_food, zona=alentejo_algarve, proteina=carne]).
example(9, [faixa=i16_30, dieta=geral, zona=norte_centro, proteina=peixe]).
example(10, [faixa=i16_30, dieta=ligeira, zona=norte_centro, proteina=peixe]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=peixe]).
example(4, [faixa=i16_30, dieta=vegana, zona=norte_centro, proteina=peixe]).
example(5, [faixa=i16_30, dieta=fast_food, zona=norte_centro, proteina=peixe]).
example(11, [faixa=i16_30, dieta=geral, zona=lisboa_vale_tejo, proteina=peixe]).
example(12, [faixa=i16_30, dieta=ligeira, zona=lisboa_vale_tejo, proteina=peixe]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=peixe]).
example(4, [faixa=i16_30, dieta=vegana, zona=lisboa_vale_tejo, proteina=peixe]).
example(5, [faixa=i16_30, dieta=fast_food, zona=lisboa_vale_tejo, proteina=peixe]).
example(13, [faixa=i16_30, dieta=geral, zona=alentejo_algarve, proteina=peixe]).
example(14, [faixa=i16_30, dieta=ligeira, zona=alentejo_algarve, proteina=peixe]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=peixe]).
example(4, [faixa=i16_30, dieta=vegana, zona=alentejo_algarve, proteina=peixe]).
example(5, [faixa=i16_30, dieta=fast_food, zona=alentejo_algarve, proteina=peixe]).
example(15, [faixa=i16_30, dieta=geral, zona=norte_centro, proteina=ovo]).
example(15, [faixa=i16_30, dieta=ligeira, zona=norte_centro, proteina=ovo]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=ovo]).
example(4, [faixa=i16_30, dieta=vegana, zona=norte_centro, proteina=ovo]).
example(5, [faixa=i16_30, dieta=fast_food, zona=norte_centro, proteina=ovo]).
example(16, [faixa=i16_30, dieta=geral, zona=lisboa_vale_tejo, proteina=ovo]).
example(16, [faixa=i16_30, dieta=ligeira, zona=lisboa_vale_tejo, proteina=ovo]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=ovo]).
example(4, [faixa=i16_30, dieta=vegana, zona=lisboa_vale_tejo, proteina=ovo]).
example(5, [faixa=i16_30, dieta=fast_food, zona=lisboa_vale_tejo, proteina=ovo]).
example(17, [faixa=i16_30, dieta=geral, zona=alentejo_algarve, proteina=ovo]).
example(17, [faixa=i16_30, dieta=ligeira, zona=alentejo_algarve, proteina=ovo]).
example(3, [faixa=i16_30, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=ovo]).
example(4, [faixa=i16_30, dieta=vegana, zona=alentejo_algarve, proteina=ovo]).
example(5, [faixa=i16_30, dieta=fast_food, zona=alentejo_algarve, proteina=ovo]).
example(18, [faixa=i31_50, dieta=geral, zona=norte_centro, proteina=carne]).
example(2, [faixa=i31_50, dieta=ligeira, zona=norte_centro, proteina=carne]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=carne]).
example(4, [faixa=i31_50, dieta=vegana, zona=norte_centro, proteina=carne]).
example(5, [faixa=i31_50, dieta=fast_food, zona=norte_centro, proteina=carne]).
example(19, [faixa=i31_50, dieta=geral, zona=lisboa_vale_tejo, proteina=carne]).
example(6, [faixa=i31_50, dieta=ligeira, zona=lisboa_vale_tejo, proteina=carne]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=carne]).
example(4, [faixa=i31_50, dieta=vegana, zona=lisboa_vale_tejo, proteina=carne]).
example(5, [faixa=i31_50, dieta=fast_food, zona=lisboa_vale_tejo, proteina=carne]).
example(20, [faixa=i31_50, dieta=geral, zona=alentejo_algarve, proteina=carne]).
example(8, [faixa=i31_50, dieta=ligeira, zona=alentejo_algarve, proteina=carne]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=carne]).
example(4, [faixa=i31_50, dieta=vegana, zona=alentejo_algarve, proteina=carne]).
example(5, [faixa=i31_50, dieta=fast_food, zona=alentejo_algarve, proteina=carne]).
example(21, [faixa=i31_50, dieta=geral, zona=norte_centro, proteina=peixe]).
example(22, [faixa=i31_50, dieta=ligeira, zona=norte_centro, proteina=peixe]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=peixe]).
example(4, [faixa=i31_50, dieta=vegana, zona=norte_centro, proteina=peixe]).
example(5, [faixa=i31_50, dieta=fast_food, zona=norte_centro, proteina=peixe]).
example(11, [faixa=i31_50, dieta=geral, zona=lisboa_vale_tejo, proteina=peixe]).
example(23, [faixa=i31_50, dieta=ligeira, zona=lisboa_vale_tejo, proteina=peixe]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=peixe]).
example(4, [faixa=i31_50, dieta=vegana, zona=lisboa_vale_tejo, proteina=peixe]).
example(5, [faixa=i31_50, dieta=fast_food, zona=lisboa_vale_tejo, proteina=peixe]).
example(24, [faixa=i31_50, dieta=geral, zona=alentejo_algarve, proteina=peixe]).
example(14, [faixa=i31_50, dieta=ligeira, zona=alentejo_algarve, proteina=peixe]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=peixe]).
example(4, [faixa=i31_50, dieta=vegana, zona=alentejo_algarve, proteina=peixe]).
example(5, [faixa=i31_50, dieta=fast_food, zona=alentejo_algarve, proteina=peixe]).
example(15, [faixa=i31_50, dieta=geral, zona=norte_centro, proteina=ovo]).
example(15, [faixa=i31_50, dieta=ligeira, zona=norte_centro, proteina=ovo]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=ovo]).
example(4, [faixa=i31_50, dieta=vegana, zona=norte_centro, proteina=ovo]).
example(5, [faixa=i31_50, dieta=fast_food, zona=norte_centro, proteina=ovo]).
example(16, [faixa=i31_50, dieta=geral, zona=lisboa_vale_tejo, proteina=ovo]).
example(16, [faixa=i31_50, dieta=ligeira, zona=lisboa_vale_tejo, proteina=ovo]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=ovo]).
example(4, [faixa=i31_50, dieta=vegana, zona=lisboa_vale_tejo, proteina=ovo]).
example(5, [faixa=i31_50, dieta=fast_food, zona=lisboa_vale_tejo, proteina=ovo]).
example(17, [faixa=i31_50, dieta=geral, zona=alentejo_algarve, proteina=ovo]).
example(17, [faixa=i31_50, dieta=ligeira, zona=alentejo_algarve, proteina=ovo]).
example(3, [faixa=i31_50, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=ovo]).
example(4, [faixa=i31_50, dieta=vegana, zona=alentejo_algarve, proteina=ovo]).
example(5, [faixa=i31_50, dieta=fast_food, zona=alentejo_algarve, proteina=ovo]).
example(25, [faixa=i51_mais, dieta=geral, zona=norte_centro, proteina=carne]).
example(26, [faixa=i51_mais, dieta=ligeira, zona=norte_centro, proteina=carne]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=carne]).
example(4, [faixa=i51_mais, dieta=vegana, zona=norte_centro, proteina=carne]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=norte_centro, proteina=carne]).
example(27, [faixa=i51_mais, dieta=geral, zona=lisboa_vale_tejo, proteina=carne]).
example(26, [faixa=i51_mais, dieta=ligeira, zona=lisboa_vale_tejo, proteina=carne]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=carne]).
example(4, [faixa=i51_mais, dieta=vegana, zona=lisboa_vale_tejo, proteina=carne]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=lisboa_vale_tejo, proteina=carne]).
example(20, [faixa=i51_mais, dieta=geral, zona=alentejo_algarve, proteina=carne]).
example(8, [faixa=i51_mais, dieta=ligeira, zona=alentejo_algarve, proteina=carne]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=carne]).
example(4, [faixa=i51_mais, dieta=vegana, zona=alentejo_algarve, proteina=carne]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=alentejo_algarve, proteina=carne]).
example(28, [faixa=i51_mais, dieta=geral, zona=norte_centro, proteina=peixe]).
example(22, [faixa=i51_mais, dieta=ligeira, zona=norte_centro, proteina=peixe]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=peixe]).
example(4, [faixa=i51_mais, dieta=vegana, zona=norte_centro, proteina=peixe]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=norte_centro, proteina=peixe]).
example(29, [faixa=i51_mais, dieta=geral, zona=lisboa_vale_tejo, proteina=peixe]).
example(23, [faixa=i51_mais, dieta=ligeira, zona=lisboa_vale_tejo, proteina=peixe]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=peixe]).
example(4, [faixa=i51_mais, dieta=vegana, zona=lisboa_vale_tejo, proteina=peixe]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=lisboa_vale_tejo, proteina=peixe]).
example(24, [faixa=i51_mais, dieta=geral, zona=alentejo_algarve, proteina=peixe]).
example(14, [faixa=i51_mais, dieta=ligeira, zona=alentejo_algarve, proteina=peixe]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=peixe]).
example(4, [faixa=i51_mais, dieta=vegana, zona=alentejo_algarve, proteina=peixe]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=alentejo_algarve, proteina=peixe]).
example(30, [faixa=i51_mais, dieta=geral, zona=norte_centro, proteina=ovo]).
example(30, [faixa=i51_mais, dieta=ligeira, zona=norte_centro, proteina=ovo]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=norte_centro, proteina=ovo]).
example(4, [faixa=i51_mais, dieta=vegana, zona=norte_centro, proteina=ovo]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=norte_centro, proteina=ovo]).
example(30, [faixa=i51_mais, dieta=geral, zona=lisboa_vale_tejo, proteina=ovo]).
example(30, [faixa=i51_mais, dieta=ligeira, zona=lisboa_vale_tejo, proteina=ovo]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=lisboa_vale_tejo, proteina=ovo]).
example(4, [faixa=i51_mais, dieta=vegana, zona=lisboa_vale_tejo, proteina=ovo]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=lisboa_vale_tejo, proteina=ovo]).
example(31, [faixa=i51_mais, dieta=geral, zona=alentejo_algarve, proteina=ovo]).
example(32, [faixa=i51_mais, dieta=ligeira, zona=alentejo_algarve, proteina=ovo]).
example(3, [faixa=i51_mais, dieta=ovo_lacteo_vegetariana, zona=alentejo_algarve, proteina=ovo]).
example(4, [faixa=i51_mais, dieta=vegana, zona=alentejo_algarve, proteina=ovo]).
example(5, [faixa=i51_mais, dieta=fast_food, zona=alentejo_algarve, proteina=ovo]).

